import React,{useEffect,useMemo,useState} from 'react';
import {Camera,Check,Heart,Layers3,Shirt,Sparkles,Video} from 'lucide-react';
import {Product,GarmentColorOption} from '../types';
import {SAMPLE_PRODUCTS,STANDARD_GARMENT_COLORS} from '../data/catalog';
import {Language} from '../i18n/translations';
import {LiveCameraTryOn} from './LiveCameraTryOn';
interface Props{isCameraActive:boolean;videoRef:React.RefObject<HTMLVideoElement>;onLogEvent:(event:string,details?:any)=>void;onToggleCamera:()=>void;lang:Language}
export const FittingRoom:React.FC<Props>=({isCameraActive,videoRef,onLogEvent,onToggleCamera,lang})=>{
 const fa=lang==='fa'; const [product,setProduct]=useState<Product>(SAMPLE_PRODUCTS[0]); const [color,setColor]=useState<GarmentColorOption>(STANDARD_GARMENT_COLORS[0]); const [liked,setLiked]=useState(false); const [category,setCategory]=useState<string>('all');
 useEffect(()=>{if(isCameraActive)onLogEvent('REFERENCE_FITTING_ROOM_LIVE')},[isCameraActive]);
 const products=useMemo(()=>SAMPLE_PRODUCTS.filter(p=>category==='all'||p.category===category),[category]);
 const categories=[['all',fa?'همه':'All'],['upper_body',fa?'پیراهن':'Tops'],['jackets',fa?'کت و ژاکت':'Jackets'],['dresses',fa?'لباس کامل':'Dresses']];
 const choose=(p:Product)=>{setProduct(p);onLogEvent('GARMENT_SELECTED',{productId:p.id,name:p.name})};
 return <div className="fitai-reference-shell"><section className="fitai-reference-hero"><div><div className="fitai-kicker"><Sparkles/> {fa?'اتاق پرو هوشمند':'AI FITTING ROOM'}</div><h1>{fa?'لباس را روی خودت ببین، قبل از خرید':'See the look before you buy'}</h1><p>{fa?'دوربین زنده، تشخیص وضعیت بدن و ترکیب لباس روی تصویر واقعی؛ بدون تغییر نسبت چهره و بدن.':'Live camera, real pose analysis and garment compositing without stretching your body or face.'}</p></div><button className={isCameraActive?'fitai-camera active':'fitai-camera'} onClick={onToggleCamera}><Camera/>{isCameraActive?(fa?'دوربین روشن است':'Camera live'):(fa?'روشن کردن دوربین':'Start camera')}</button></section>
 <div className="fitai-workspace"><aside className="fitai-panel fitai-catalog"><div className="fitai-panel-title"><div><span>{fa?'انتخاب لباس':'Choose garment'}</span><small>{fa?'کاتالوگ فروشگاه':'STORE CATALOG'}</small></div><Shirt/></div><div className="fitai-category-row">{categories.map(([id,label])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}>{label}</button>)}</div><div className="fitai-product-list">{products.slice(0,5).map(p=><button key={p.id} onClick={()=>choose(p)} className={product.id===p.id?'fitai-product active':'fitai-product'}><img src={p.imageUrl} alt=""/><div><strong>{p.name}</strong><span>{p.fabric} · {p.sizes.join(' / ')}</span><b>{p.price}</b></div>{product.id===p.id&&<Check/>}</button>)}</div><div className="fitai-color-block"><span>{fa?'رنگ لباس':'Garment color'}</span><div>{STANDARD_GARMENT_COLORS.slice(0,8).map(c=><button key={c.id} title={fa?c.nameFa:c.nameEn} onClick={()=>setColor(c)} className={color.id===c.id?'active':''} style={{background:c.hex}}/>)}</div></div></aside>
 <main className="fitai-stage-card"><div className="fitai-stage-head"><div><Video/><span>{fa?'آینه زنده':'LIVE MIRROR'}</span></div><div className={isCameraActive?'fitai-status online':'fitai-status'}>{isCameraActive?(fa?'پردازش زنده':'LIVE'):(fa?'آماده':'READY')}</div></div><LiveCameraTryOn videoRef={videoRef} isCameraActive={isCameraActive} onToggleCamera={onToggleCamera} selectedProduct={product} selectedColor={color} landmarks={[]} lang={lang}/><div className="fitai-stage-caption"><div><strong>{product.name}</strong><span>{fa?'ترکیب محلی لباس + Pose + ماسک جداسازی بدن':'Local garment + pose + person-mask compositor'}</span></div><button onClick={()=>setLiked(v=>!v)} className={liked?'liked':''}><Heart fill={liked?'currentColor':'none'}/>{fa?'پسندیدم':'Like'}</button></div></main>
 <aside className="fitai-panel fitai-details"><div className="fitai-panel-title"><div><span>{fa?'استایل انتخاب‌شده':'Selected look'}</span><small>{fa?'جزئیات زنده':'LIVE DETAILS'}</small></div><Layers3/></div><div className="fitai-look-card"><div className="fitai-look-icon"><Shirt/></div><strong>{product.name}</strong><span>{product.description}</span></div><div className="fitai-spec"><span>{fa?'پارچه':'Fabric'}</span><b>{product.fabric}</b></div><div className="fitai-spec"><span>{fa?'رنگ':'Color'}</span><b><i style={{background:color.hex}}/>{fa?color.nameFa:color.nameEn}</b></div><div className="fitai-spec"><span>{fa?'سایزهای موجود':'Available sizes'}</span><b>{product.sizes.join(' · ')}</b></div><div className="fitai-truth-note"><Sparkles/><div><strong>{fa?'رندر واقعی، نه اطلاعات ساختگی':'Truthful rendering'}</strong><p>{fa?'اندازه سانتی‌متری، هویت چهره و نتیجه مولد تا زمان نصب مدل معتبر نمایش داده نمی‌شوند.':'Metric sizing, face identity and generative output stay hidden until real providers are installed.'}</p></div></div></aside></div></div>
}